### ISSUE TITLE
Formatting tweak

### ISSUE THREAD

**Issue by bilogic** [cubiclesoft/php-libs-to-composer#1]
```PHP
<?php
	namespace CubicleSoft;
?><?php // can this line be removed?
	...
```

Hi, great set of codes here!

Just wondering if the `?><?php` can be removed? It is causing my code helper not to recognize the namespace and classname. Thank you!

**Comment by cubiclesoft** [comment]
The namespace comes from the nightly [automatic namespacing repository](https://github.com/cubiclesoft/php-libs-namespaced).  CubicleSoft classes are not namespaced by default since there is no need to do so as there are minimal 3rd party dependencies spanning 85+ repos.

These classes are two steps removed from the original source code and the issue is better handled over on the namespace libs repo.
